# mise.toml
# Defines mise tools and task includes for this repo.
# Does not install tools automatically on its own.

[tools]
chezmoi = "2.69.3"
neovim = "0.11.6"
python = "3.14.3"
go = "1.25.7"
rust = "1.93.0"
kubectl = "1.35.0"
kubectx = "0.9.5"
k9s = "0.50.18"
gofumpt = "0.9.2"
golangci-lint = "2.8.0"
goreleaser = "2.13.3"
mockery = "3.6.3"
fzf = "0.67.0"
ripgrep = "15.1.0"
fd = "10.2.0"

