# mise.toml
# Defines mise tools and task includes for this repo.
# Does not install tools automatically on its own.

[tools]
chezmoi = "latest"
neovim = "latest"
python = "latest"
go = "latest"
rust = "latest"
kubectl = "latest"
kubectx = "latest"
k9s = "latest"
gofumpt = "latest"
golangci-lint = "latest"
goreleaser = "latest"
mockery = "latest"
fzf = "latest"
